// Shared presentation and browser ceremony for all public sign-in/setup routes.
// Authentication policy, challenges, and session creation remain in their route handlers.
const escapeHtml = (value: string) => value.replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);
const scriptValue = (value: unknown) => JSON.stringify(value).replace(/</g, "\\u003c");

const styles = `
*{box-sizing:border-box}html{color-scheme:dark}body{margin:0;background:#101214;color:#eef0e8;font:15px system-ui;min-height:100svh;display:grid;place-items:center;padding:40px 0;overflow-x:hidden}
.glow{position:fixed;inset:20% auto auto 35%;width:320px;height:320px;border-radius:50%;background:#9ec68a;filter:blur(120px);opacity:.12;pointer-events:none;animation:float 9s ease-in-out infinite alternate}
main{position:relative;width:min(390px,calc(100% - 40px));animation:enter .7s ease-out}header{display:flex;align-items:center;gap:10px;margin-bottom:58px;font-weight:600}.logo{background:#c9e8ae;color:#18221b;border-radius:12px;padding:9px 12px}
small,label{color:#9ca69d;font-size:12px}h1{font-size:40px;line-height:1.15;letter-spacing:-1.8px;font-weight:500;margin:14px 0}p{color:#a7afa8;line-height:1.6;margin:0 0 30px}
button,input,.button{width:100%;font:inherit;border-radius:14px;padding:17px;border:1px solid #373e36;background:transparent;color:inherit}button,.button{cursor:pointer;transition:transform .2s,background .2s;text-align:center;display:block;text-decoration:none}button:hover:not(:disabled),.button:hover{background:#252b25;transform:translateY(-2px)}
.primary{background:#c9e8ae;border-color:#c9e8ae;color:#19251b;font-weight:650}.primary:hover:not(:disabled){background:#def2cc}.secondary{margin-top:12px}.quiet{border:0;color:#9ca69d;padding:12px;font-size:13px}button:disabled{opacity:.6;cursor:wait}button:focus-visible,a:focus-visible,summary:focus-visible,input:focus-visible{outline:2px solid #c9e8ae;outline-offset:4px}
.foot{margin-top:36px;text-align:center;line-height:1.8;overflow-wrap:anywhere}input{display:block;margin:8px 0 12px;background:#181d19;font-size:16px}form{margin-top:18px}form[hidden]{display:none}#status{min-height:28px;color:#c9e8ae;font-size:13px;margin:14px 0 0;overflow-wrap:anywhere}#status.error{color:#efaaa3}details{margin-top:14px;color:#9ca69d;font-size:13px}summary{cursor:pointer;padding:12px;text-align:center}details button{margin-top:8px}.back{display:block;color:#a7afa8;text-align:center;margin-top:18px}noscript{display:block;color:#efaaa3;margin-top:16px}
@keyframes float{to{transform:translate(40px,-50px)}}@keyframes enter{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:none}}@media(max-height:700px){body{padding:28px 0}header{margin-bottom:32px}.foot{margin-top:24px}}@media(prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}
`;

export function renderLoginPage(options: { methods: readonly string[]; setupToken?: string; passkeyOnly?: boolean }) {
  const { methods, setupToken, passkeyOnly = false } = options;
  const setup = setupToken !== undefined;
  const hasPasskey = methods.includes("passkey");
  const hasPassword = methods.includes("password") && !passkeyOnly;
  const form = (method: string, label: string, hidden = false) => `<form id="${method}" data-method="${method}" ${hidden ? "hidden" : ""}><label for="${method}-secret">${label}</label><input id="${method}-secret" name="secret" type="password" autocomplete="${setup ? "new-password" : method === "password" ? "current-password" : "off"}" ${setup ? 'minlength="12" maxlength="1024"' : ""} required>${setup ? '<label for="confirm">Confirm password</label><input id="confirm" name="confirm" type="password" autocomplete="new-password" required>' : ""}<button class="primary">${setup ? "Set password" : "Sign in"}</button></form>`;
  const passkey = !hasPasskey ? "" : setup && !passkeyOnly
    ? `<a class="button primary" href="/api/auth/passkey-bootstrap?token=${escapeHtml(encodeURIComponent(setupToken!))}">Set up a passkey</a>`
    : `${setup ? '<label for="name">Credential name</label><input id="name" value="Primary passkey" maxlength="80" autocomplete="off">' : ""}<button class="primary" id="go"><span aria-hidden="true">◈ &nbsp;</span>${setup ? "Create passkey" : "Sign in with passkey"}</button>`;
  const alternatives = !setup && !passkeyOnly ? [
    methods.includes("external") ? '<form data-method="external"><button>Continue with trusted proxy</button></form>' : "",
    methods.includes("legacy") ? form("legacy", "Legacy token (deprecated)") : "",
  ].join("") : "";
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>pi-web · ${setup ? "Set up" : "Sign in"}</title><style>${styles}</style></head><body><div class="glow" aria-hidden="true"></div><main><header><span class="logo" aria-hidden="true">p</span>pi-web</header><small>YOUR PRIVATE WORKSPACE</small><h1>${setup ? (passkeyOnly ? "Enroll a passkey." : "Make yourself at home.") : "Welcome back."}</h1><p>${setup ? "Choose a sign-in method for your private workspace. Keep a backup credential and terminal recovery access." : "Your agents. Your space.<br>Pick up where you left off."}</p>${passkey}${hasPassword && hasPasskey && !setup ? '<button class="secondary" id="passwordToggle" aria-expanded="false" aria-controls="password">Use a password</button>' : ""}${hasPassword ? form("password", setup ? "New password (12+ characters)" : "Password", hasPasskey && !setup) : ""}${alternatives ? `<details><summary>Other ways to sign in</summary>${alternatives}</details>` : ""}${!methods.length ? '<p>No sign-in method is available. Use terminal recovery to restore access.</p>' : ""}${passkeyOnly && !setup ? '<a class="back" href="/api/auth/login">Other sign-in methods</a>' : ""}<p id="status" role="status" aria-live="polite" aria-atomic="true"></p><noscript>JavaScript is required to sign in. Enable it and reload this page.</noscript><footer class="foot"><small id="host"></small><br><small id="connection"></small><button class="quiet" id="clear">Clear this browser session</button></footer></main><script>
const statusElement=document.getElementById('status'),go=document.getElementById('go'),setup=${scriptValue(setup)},setupToken=${scriptValue(setupToken || "")};
const report=(message,error=false)=>{statusElement.textContent=message;statusElement.classList.toggle('error',error)};
document.getElementById('host').textContent=location.host;
document.getElementById('connection').textContent=location.protocol==='https:'?'Private connection · Your workspace':(window.isSecureContext?'Local connection · Your workspace':'Unencrypted connection · Use HTTPS remotely');
const toggle=document.getElementById('passwordToggle');if(toggle)toggle.onclick=()=>{const f=document.getElementById('password');f.hidden=!f.hidden;toggle.setAttribute('aria-expanded',String(!f.hidden));if(!f.hidden)f.elements.secret.focus()};
const post=async(path,body,headers={})=>{const r=await fetch(path,{method:'POST',headers:{'content-type':'application/json',...headers},body:JSON.stringify(body)});const value=await r.json().catch(()=>({}));if(!r.ok)throw Error(value.error||'Request failed ('+r.status+')');return value};
let busy=false;const run=async(action,message)=>{if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);report(message);try{await action()}catch(error){report(error.name==='NotAllowedError'?'Passkey request cancelled or unavailable. Try again, or choose another sign-in method.':error.message||'Unable to sign in. Please try again.',true)}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false)}};
document.getElementById('clear').onclick=()=>run(async()=>{await post('/api/auth/logout',{}, {'x-pi-web-client-id':'explicit-logout'});try{localStorage.removeItem('pi-web-token')}catch{}location.href='/'},'Clearing this browser session…');
document.querySelectorAll('form').forEach(f=>f.addEventListener('submit',event=>{event.preventDefault();run(async()=>{if(setup&&f.elements.secret.value!==f.elements.confirm.value)throw Error('Passwords do not match');await post('/api/auth/'+f.dataset.method+(setup?'/bootstrap':'/login'),{password:f.elements.secret?.value,token:setupToken});location.href='/'},setup?'Setting up your workspace…':'Signing in…')}));
const decode=v=>Uint8Array.from(atob(v.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0)),encode=v=>btoa(String.fromCharCode(...new Uint8Array(v))).replace(/\\+/g,'-').replace(/\\//g,'_').replace(/=+$/,'');
if(go)go.onclick=()=>run(async()=>{if(!window.isSecureContext||!window.PublicKeyCredential)throw Error('Passkeys require a supported browser on HTTPS or localhost. Choose another sign-in method.');const name=document.getElementById('name')?.value||'Passkey';const o=await post(setup?'/api/auth/bootstrap/options':'/api/auth/passkey/options',setup?{token:setupToken,name}:{});o.challenge=decode(o.challenge);if(setup){o.user.id=decode(o.user.id);o.excludeCredentials?.forEach(x=>x.id=decode(x.id))}else{o.allowCredentials?.forEach(x=>x.id=decode(x.id))}const c=setup?await navigator.credentials.create({publicKey:o}):await navigator.credentials.get({publicKey:o});if(!c)throw Error('Passkey request cancelled. Please try again.');const response={id:c.id,rawId:encode(c.rawId),type:c.type,response:{clientDataJSON:encode(c.response.clientDataJSON),authenticatorData:c.response.authenticatorData&&encode(c.response.authenticatorData),signature:c.response.signature&&encode(c.response.signature),userHandle:c.response.userHandle&&encode(c.response.userHandle),attestationObject:c.response.attestationObject&&encode(c.response.attestationObject)},clientExtensionResults:c.getClientExtensionResults()};await post(setup?'/api/auth/bootstrap/verify':'/api/auth/passkey/verify',setup?{response,name}:response);location.href='/'},'Waiting for your device’s passkey prompt…');
</script></body></html>`;
}
