import { randomUUID } from "node:crypto";
import type { IncomingMessage, ServerResponse } from "node:http";
import { generateRegistrationOptions, verifyRegistrationResponse, type RegistrationResponseJSON } from "@simplewebauthn/server";
import { hashSecret, randomSecret, type AuthKernel, type AuthStore, type GateResult } from "./kernel.js";
import type { PasskeyConfig } from "./passkey.js";

const DAY = 86_400_000;
const registrations = new Map<string, { expiresAt: number; name: string; grantHash?: string }>();
function send(res: ServerResponse, status: number, value: unknown) { const text = JSON.stringify(value); res.writeHead(status, { "content-type": "application/json", "cache-control": "no-store" }); res.end(text); }
async function input(req: IncomingMessage) { const chunks: Buffer[] = []; let n = 0; for await (const chunk of req) { n += chunk.length; if (n > 1_000_000) throw new Error("Body too large"); chunks.push(chunk); } return JSON.parse(Buffer.concat(chunks).toString() || "{}"); }
function challengeOf(response: unknown) { try { const encoded = (response as any)?.response?.clientDataJSON; const parsed = JSON.parse(Buffer.from(encoded, "base64url").toString()); return typeof parsed.challenge === "string" ? parsed.challenge : undefined; } catch { return undefined; } }
function sweep() { const now = Date.now(); for (const [key, value] of registrations) if (value.expiresAt <= now) registrations.delete(key); while (registrations.size >= 256) registrations.delete(registrations.keys().next().value!); }
const bytes64 = (value: Uint8Array) => Buffer.from(value).toString("base64url");

export async function handlePublicDeviceGrant(req: IncomingMessage, res: ServerResponse, url: URL, kernel: AuthKernel, store: AuthStore, config: PasskeyConfig) {
  if (req.method === "GET" && url.pathname === "/api/auth/device") {
    const grant = url.searchParams.get("grant") || ""; const passkey = kernel.mode === "passkey";
    const html = `<!doctype html><meta name="viewport" content="width=device-width"><title>Add device</title><style>body{font:16px system-ui;max-width:32rem;margin:12vh auto;padding:2rem}button,input{font:inherit;padding:.7rem;width:100%;margin:.4rem}</style><h1>Add this device</h1>${passkey ? '<input id="name" value="Device passkey">' : ""}<button id="go">Continue</button><p id="status"></p><script>const goButton=document.getElementById('go'),statusElement=document.getElementById('status'),nameInput=document.getElementById('name'),cv=v=>Uint8Array.from(atob(v.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0)),enc=v=>btoa(String.fromCharCode(...new Uint8Array(v))).replace(/\\+/g,'-').replace(/\\//g,'_').replace(/=+$/,'');goButton.onclick=async()=>{try{${passkey ? `let o=await fetch('/api/auth/device/passkey/options',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({grant:${JSON.stringify(grant)},name:nameInput?.value||'Added device'})}).then(r=>r.json());o.challenge=cv(o.challenge);o.user.id=cv(o.user.id);o.excludeCredentials?.forEach(x=>x.id=cv(x.id));const c=await navigator.credentials.create({publicKey:o});const response={id:c.id,rawId:enc(c.rawId),type:c.type,response:{clientDataJSON:enc(c.response.clientDataJSON),attestationObject:enc(c.response.attestationObject)},clientExtensionResults:c.getClientExtensionResults()};await fetch('/api/auth/device/passkey/verify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({response})}).then(r=>{if(!r.ok)throw Error('Grant failed')});` : `await fetch('/api/auth/device/redeem',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({grant:${JSON.stringify(grant)}})}).then(r=>{if(!r.ok)throw Error('Grant failed')});`}location.href='/'}catch(e){statusElement.textContent=e.message}}</script>`;
    res.writeHead(200, { "content-type": "text/html; charset=utf-8", "cache-control": "no-store", "content-security-policy": "default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; connect-src 'self'" }); res.end(html); return true;
  }
  if (req.method === "POST" && url.pathname === "/api/auth/device/redeem" && kernel.mode === "legacy") {
    const body = await input(req) as { grant?: string }; const hash = hashSecret(body.grant || ""); let valid = false;
    await store.update(state => { const grant = (state.deviceGrants || []).find(g => g.hash === hash && !g.usedAt && !g.cancelledAt && g.expiresAt > Date.now()); if (grant) { grant.usedAt = Date.now(); valid = true; } });
    if (!valid) return send(res, 401, { ok: false, error: "Invalid or expired device grant" });
    await kernel.establishSession(res, { id: "legacy:device", displayName: "Added device" }); send(res, 200, { ok: true }); return true;
  }
  if (req.method === "POST" && url.pathname === "/api/auth/device/passkey/options" && kernel.mode === "passkey") {
    const body = await input(req) as { grant?: string; name?: string }; const state = await store.read(); const hash = hashSecret(body.grant || "");
    const grant = (state.deviceGrants || []).find(g => g.hash === hash && !g.usedAt && !g.cancelledAt && g.expiresAt > Date.now());
    if (!grant) { send(res, 401, { ok: false, error: "Invalid or expired device grant" }); return true; }
    const options = await generateRegistrationOptions({ rpName: config.rpName, rpID: config.rpID, userName: "pi-web-owner", userDisplayName: "Pi Web Owner", attestationType: "none", authenticatorSelection: { residentKey: "preferred", userVerification: "required" }, excludeCredentials: state.credentials.filter(c => !c.revokedAt).map(c => ({ id: c.id })) });
    sweep(); registrations.set(options.challenge, { expiresAt: Date.now() + 120_000, name: body.name?.slice(0, 80) || "Added device", grantHash: hash }); send(res, 200, options); return true;
  }
  if (req.method === "POST" && url.pathname === "/api/auth/device/passkey/verify" && kernel.mode === "passkey") {
    const body = await input(req) as { response?: RegistrationResponseJSON }; const challenge = challengeOf(body.response); const pending = challenge ? registrations.get(challenge) : undefined;
    if (!challenge || !pending || !pending.grantHash || pending.expiresAt <= Date.now() || !registrations.delete(challenge)) { send(res, 400, { ok: false, error: "Expired challenge" }); return true; }
    const result = await verifyRegistrationResponse({ response: body.response!, expectedChallenge: challenge, expectedOrigin: config.origin, expectedRPID: config.rpID, requireUserVerification: true });
    if (!result.verified || !result.registrationInfo) { send(res, 401, { ok: false, error: "Verification failed" }); return true; } const credential = result.registrationInfo.credential; let valid = false;
    await store.update(state => { const grant = (state.deviceGrants || []).find(g => g.hash === pending.grantHash && !g.usedAt && !g.cancelledAt && g.expiresAt > Date.now()); if (!grant) return; grant.usedAt = Date.now(); state.credentials.push({ id: credential.id, publicKey: bytes64(credential.publicKey), counter: credential.counter, transports: credential.transports, name: pending.name, createdAt: Date.now() }); valid = true; });
    if (!valid) { send(res, 409, { ok: false, error: "Device grant already used" }); return true; } await kernel.establishSession(res, { id: "passkey:owner", displayName: "Owner" }); send(res, 200, { ok: true }); return true;
  }
  return false;
}

export async function handleSecurityRoute(req: IncomingMessage, res: ServerResponse, url: URL, auth: Extract<GateResult, { ok: true }>, kernel: AuthKernel, store: AuthStore, config: PasskeyConfig) {
  if (!url.pathname.startsWith("/api/auth/")) return false;
  const state = await store.read(); const now = Date.now();
  if (req.method === "GET" && url.pathname === "/api/auth/info") { send(res, 200, { mode: kernel.mode, identity: auth.identity }); return true; }
  const requireSession = () => { if (auth.via === "session") return true; send(res, 403, { ok: false, error: "A browser session is required" }); return false; };
  if (req.method === "GET" && url.pathname === "/api/auth/security") { if (!requireSession()) return true; send(res, 200, { mode: kernel.mode, identity: auth.identity, passkeys: state.credentials.filter(c => !c.revokedAt).map(({ publicKey, counter, ...c }) => c), sessions: state.sessions.filter(s => !s.revokedAt && s.expiresAt > now).map(({ hash, ...s }) => ({ ...s, id: hashSecret(hash), current: hash === auth.sessionHash })), apiTokens: state.apiTokens.filter(t => !t.revokedAt).map(({ hash, ...t }) => t), deviceGrants: (state.deviceGrants || []).filter(g => !g.usedAt && !g.cancelledAt && g.expiresAt > now).map(({ hash, createdBySessionHash, ...g }) => g) }); return true; }
  if (req.method === "POST" && url.pathname === "/api/auth/tokens") { if (!requireSession()) return true; const b = await input(req) as { name?: string; days?: number }; const secret = `piw_${randomSecret()}`, id = randomUUID(), days = Math.max(1, Math.min(365, Number(b.days) || 30)); await store.update(s => { s.apiTokens.push({ id, name: b.name?.slice(0, 80) || "API token", hash: hashSecret(secret), createdAt: now, expiresAt: now + days * DAY }); }); send(res, 201, { id, secret }); return true; }
  let match = /^\/api\/auth\/tokens\/([^/]+)$/.exec(url.pathname); if (req.method === "DELETE" && match) { if (!requireSession()) return true; let found = false; await store.update(s => { const item = s.apiTokens.find(x => x.id === match![1] && !x.revokedAt); if (item) { item.revokedAt = now; found = true; } }); send(res, found ? 200 : 404, found ? { ok: true } : { ok: false, error: "API token not found" }); return true; }
  match = /^\/api\/auth\/sessions\/([^/]+)$/.exec(url.pathname); if (req.method === "DELETE" && match) { if (!requireSession()) return true; let found = false; await store.update(s => { const item = s.sessions.find(x => x.hash === match![1] || hashSecret(x.hash) === match![1]); if (item) { item.revokedAt = now; found = true; } }); send(res, found ? 200 : 404, found ? { ok: true } : { ok: false, error: "Session not found" }); return true; }
  match = /^\/api\/auth\/passkeys\/([^/]+)$/.exec(url.pathname); if (req.method === "DELETE" && match) { if (!requireSession()) return true; let found = false; await store.update(s => { const item = s.credentials.find(x => x.id === decodeURIComponent(match![1]) && !x.revokedAt); if (item) { item.revokedAt = now; found = true; for (const session of s.sessions) session.revokedAt = now; } }); if (found) kernel.clearSession(res); send(res, found ? 200 : 404, found ? { ok: true } : { ok: false, error: "Passkey not found" }); return true; }
  if (req.method === "POST" && url.pathname === "/api/auth/device-grants") { if (auth.via !== "session" || !auth.sessionHash) { send(res, 403, { ok: false, error: "A browser session is required" }); return true; } const secret = randomSecret(), id = randomUUID(); await store.update(s => { (s.deviceGrants ||= []).push({ id, hash: hashSecret(secret), createdAt: now, expiresAt: now + 120_000, createdBy: auth.identity, createdBySessionHash: auth.sessionHash! }); }); send(res, 201, { id, secret, expiresAt: now + 120_000, url: `${config.origin}/api/auth/device?grant=${encodeURIComponent(secret)}` }); return true; }
  match = /^\/api\/auth\/device-grants\/([^/]+)$/.exec(url.pathname); if (req.method === "DELETE" && match) { if (!requireSession()) return true; let found = false; await store.update(s => { const grant = (s.deviceGrants || []).find(g => g.id === match![1] && g.createdBySessionHash === auth.sessionHash && !g.usedAt && !g.cancelledAt); if (grant) { grant.cancelledAt = now; found = true; } }); send(res, found ? 200 : 404, found ? { ok: true } : { ok: false, error: "Device grant not found" }); return true; }
  if (req.method === "POST" && url.pathname === "/api/auth/passkeys/options") { if (kernel.mode !== "passkey" || auth.via !== "session") { send(res, 403, { ok: false, error: "A passkey session is required" }); return true; } const b = await input(req) as { name?: string }; const options = await generateRegistrationOptions({ rpName: config.rpName, rpID: config.rpID, userName: "pi-web-owner", userDisplayName: "Pi Web Owner", attestationType: "none", authenticatorSelection: { userVerification: "required" }, excludeCredentials: state.credentials.filter(c => !c.revokedAt).map(c => ({ id: c.id })) }); sweep(); registrations.set(options.challenge, { expiresAt: now + 120_000, name: b.name?.slice(0, 80) || "Passkey" }); send(res, 200, options); return true; }
  if (req.method === "POST" && url.pathname === "/api/auth/passkeys/verify") { const b = await input(req) as { response?: RegistrationResponseJSON }; const challenge = challengeOf(b.response), pending = challenge ? registrations.get(challenge) : undefined; if (!challenge || !pending || pending.grantHash || pending.expiresAt <= now || !registrations.delete(challenge)) { send(res, 400, { ok: false, error: "Expired challenge" }); return true; } const result = await verifyRegistrationResponse({ response: b.response!, expectedChallenge: challenge, expectedOrigin: config.origin, expectedRPID: config.rpID, requireUserVerification: true }); if (!result.verified || !result.registrationInfo) { send(res, 401, { ok: false }); return true; } const c = result.registrationInfo.credential; await store.update(s => { s.credentials.push({ id: c.id, publicKey: bytes64(c.publicKey), counter: c.counter, transports: c.transports, name: pending.name, createdAt: now }); }); send(res, 201, { ok: true }); return true; }
  return false;
}
